project:
  type: website

website:
  title: "LatinDiab"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right: 
      - text: Work packages
        menu: 
        - wp1.qmd
        - wp2.qmd
        - wp3.qmd
        - wp4.qmd
        - wp5.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

