project:
  type: website

website:
  title: "LatinDiab"
  navbar:
    left:
      - href: index.qmd
        text: Overview
      - about.qmd
    right: 
      - text: Road map
        menu: 
        - overview.qmd
        - wp1.qmd
        - wp2.qmd
        - wp3.qmd
        - wp4.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

