---
title: "Work package 1"
---

This WP has three objectives, 1) to lead the overall management of the project, 2) to coordinate the collaboration between WPs and 3) ensure the transfer of technical skills for the implementation of the open-source software, and the implementation of a high-quality technical documentation of the project following open science and reproducibility principles.

WP1 will implement the Seedcase Project, an open-source data infrastructure tool that is compliant with the FAIR principles (**F**indable, **A**ccessible, **I**nteroperable**, R**eusable). It is designed to support modern, scalable, and efficient approaches to health information systems \[REF-seedcase webpage\]. By using state-of-the-art software engineering practices, Seedcase project ensures that health data are FAIR, meeting a robust stewardship, open and reproducible science. This will enable the integration of high quality, standardized registry data from Argentina, Mexico and Colombia into a shared framework. By documenting the full data life cycle, from generation to analysis and interpretation, Seedcase will deliver transparent, reproducible and policy-relevant data resources for research, health system planning, and decision making within diabetes care \[REF sprout webpage\].

WP1 will deploy the technical infrastructure and build local technical capacity to maintain and expand these systems, prioritizing sustainability (maintainability over time), capacity building and equity in digital health. The emphasis on co-design and open documentation ensures that the implementation of Seedcase is context-specific, scalable, and potentially transferable to other non-communicable diseases. This approach strengthens health system resilience, foster collaboration across countries, and provides a blueprint for future cooperation in digital health innovation. Figure 1 provides a graphical summary of the Seedcase-Sprout package.

\[Figure 1.\](figure1-latindiab.png)

Usage of this software tool depends on the quality of its documentation and training material, for WP2-WP4 there will be a tech lead who will liaise between WP1 training activities and local data and research practices. Two key elements in WP1 are the research operations that will simplify, streamline, and automate the collaborations and coordination of activities and products between WPs; and the technical and research capacity building that will provide the learning environment of the required technical skills in the use of modern data engineering tools through formal and informal training sessions, creating and running short workshops, and tutorials that will teach the LatinDiab members how they can use this software tool, and local data engineers on how to implement it.
