---
title: "Work package 4"
---

Established in 1943, the Mexican Institute for Social Security (IMSS by its acronym in Spanish) is Mexico’s largest public health institution, responsible for delivering medical care, social security benefits, and pension services to formally employed individuals, retirees, and their dependents such as spouses, children, and in some cases, parents and other dependents, who are legally recognized under IMSS regulations. By the end of 2024, IMSS served a total of 77,430,917 beneficiaries which represent 58.5% of the Mexican population (IMSS, 2025). 

Between 2000 and 2018, institutional health data from the IMSS revealed fluctuating but concerning trends in the incidence of T1D among children and adolescents under 19 years of age. Initial increases from 3.4 to 6.2 cases per 100,000 insured individuals between 2000 and 2006 were followed by variable peaks and declines (Gómez-Díaz RA et al. 2012; Wacher NH et al. 2020). The overall incidence slightly declined to 2.83 by 2018, age-specific and sex-specific analyses showed persistent growth in older pediatric groups (10–19 years), with adolescent females consistently exhibiting higher rates than males (Wacher NH et al. 2020). People living with T1D affiliated to IMSS face a complex set of clinical and social challenges that demand urgent attention. Most people showed poor glycemic control, had a high prevalence of complications (microvascular in 64.1% of cases) and frequent episodes of hypoglycemia and ketoacidosis, which led to high rates of emergency room visits (39%) and hospitalizations (33.9%). 

A series of databases from IMSS’ Health Information System comprises a comprehensive set of components and modules that document healthcare delivery processes. The system is designed to generate and disseminate statistical information that supports institutional decision-making. Data includes information on morbidity, mortality, births, population demographics, health services coverage, and the availability of human, infrastructural, material, and financial resources. We will use these datasets to implement the open-source software tool for the set-up of the diabetes register.

The absence of comprehensive registries for T1D impedes outcome monitoring, intervention evaluation, and equitable access to specialized care. Addressing these gaps through targeted research and implementation efforts is essential to reduce long-term complications and improve health outcomes among IMSS patients. Thus, a T1D registry would be a strategic asset for IMSS, enabling real-time tracking of clinical outcomes, identification of high-risk individuals, and monitoring of treatment adherence. By integrating sociodemographic and clinical data, IMSS could design targeted interventions, optimize resource allocation, and assess program effectiveness. Furthermore, the registry could inform policy decisions related to disability benefits, preventive care, and endocrinology service planning, shifting the focus from reactive crisis management to proactive, long-term health strategies and cost containment.

WP4 will be implemented within the IMSS to explore how routinely collected clinical and administrative data can be leveraged to standardize and enhance epidemiologic monitoring, and decision making. WP4 seeks to demonstrate how strategic data use within IMSS can serve as a scalable model for improving chronic disease management and advancing health equity across Mexico.
